version: '3'
services:
    postgres:
        image: 'postgres:latest'
        restart: always
        environment: 
             - POSTGRES_PASSWORD=postgres
        volumes: 
             - ./database:./
        ports:
             - '5432:5432'
    scraper:
        build:
            context: ./scraper
        volumes: 
             - ./scraper:/scraper
    interface_api:
        build:
            context: ./interface_api
        volumes: 
             - ./interface_api:/interface_api
        restart: always
        ports:
            - '5000:5000'