version: '3'
services:
    postgres:
        image: 'postgres:latest'
        restart: always
        environment: 
             - POSTGRES_PASSWORD='ilikepostgresalot!@#$'
        volumes: 
             - ./database:/var/lib/postgresql/data
        ports:
             - '5432:5432'
    scraper:
        build:
            context: ./scraper
        volumes: 
             - ./scraper:/scraper
        depends_on: 
             - 'interface_api'
    interface_api:
        build:
            context: ./interface_api
        volumes: 
             - ./interface_api:/interface_api
        restart: always
        ports:
            - '5000:5000'
        depends_on: 
             - 'postgres'